### ISSUE TITLE
[User feedback] Reddit prompt to open the current post in their app vs Chrome sends user to the Play Store instead of their app

### ISSUE THREAD

**Issue by dan-alcantara-neeva** [neevaco/neeva-android#852] opened 2022-08-01 22:42 UTC

**Comment by Kokobe** [comment] 2022-10-07 22:13
WebLayerShell seems to do this automatically, which is weird: 

https://user-images.githubusercontent.com/20916043/194669808-ccc2b5d6-634d-446f-b0c8-a703164754bf.mp4


This is the current behavior of our app:

https://user-images.githubusercontent.com/20916043/194669898-7d54e44f-c766-4436-837f-4276e766578d.mp4

**Comment by Kokobe** [comment] 2022-10-07 23:56
Found this [InterceptNavigationDelegateClientImpl](https://source.chromium.org/chromium/chromium/src/+/main:weblayer/browser/java/org/chromium/weblayer_private/InterceptNavigationDelegateClientImpl.java;l=151;drc=8d399817282e3c12ed54eb23ec42a5e418298ec6), will start adding logs to understand it.

**Comment by Kokobe** [comment] 2022-10-12 21:18
<img width="1423" alt="Screen Shot 2022-10-12 at 2 16 47 PM" src="https://user-images.githubusercontent.com/20916043/195449670-5e10e23b-ed3b-4cc8-8d66-0057cae19f83.png">

Logged [InterceptNavigationDelegateImpl](https://source.chromium.org/chromium/chromium/src/+/main:components/external_intents/android/java/src/org/chromium/components/external_intents/InterceptNavigationDelegateImpl.java?q=InterceptNavigationDelegateImpl&ss=chromium%2Fchromium%2Fsrc)

**Comment by Kokobe** [comment] 2022-10-12 21:38
2 interesting problems:

1. Somehow `WebLayerShell` is seeing an `https` scheme and interpreting it as "open reddit".
2. Our intent scheme urls are triggering us to go to the app store instead of the reddit app

**Comment by Kokobe** [comment] 2022-10-12 21:45
If you put WebLayerShell in incognito mode, it will do what our app does initially (but it also skips the Playstore):


https://user-images.githubusercontent.com/20916043/195453958-872275f5-7cc0-4bbc-a347-d6d563ba3299.mp4

**Comment by Kokobe** [comment] 2022-10-13 18:48
I've found that in [ExternalNavigationHandler's shouldOverrideUrlLoadingInternal](https://source.chromium.org/chromium/chromium/src/+/main:components/external_intents/android/java/src/org/chromium/components/external_intents/ExternalNavigationHandler.java;l=1591;drc=796d9f7be35cc8f766fabc6e84df424046460890;bpv=0;bpt=1), the problem is that our `resolvingInfos` variable is empty!! This doesn't happen on WebLayerShell of course

**Comment by Kokobe** [comment] 2022-10-13 19:18
Tracked this down to the android [PackageManager pm.queryIntentActivities()](https://source.chromium.org/chromium/chromium/src/+/main:base/android/java/src/org/chromium/base/PackageManagerUtils.java;drc=b375a26d4a5a6e4520442c2714d3088d3fa0d0a2;bpv=1;bpt=1;l=63) not working properly for our app...

**Comment by Kokobe** [comment] 2022-10-13 19:58
https://stackoverflow.com/questions/70107530/packagemanager-queryintentactivities-returns-empty-list-for-deeplinks

https://developer.android.com/training/package-visibility/declaring#all-apps

**Closed** 2022-10-14 02:02 UTC
Labels: bug, P1
